# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f193cde9696484da10c64fca2cc50cbd70a0362a6465334a93c82557620d35aee7c9b0ec0b162a32c8d95b6868a97ae7cca269ceb2c9d74139a95f9f36b104e8

test:
  secret_key_base: 942ec4c13f047b1c56c1f09274bb9cb69656cd9eaab2756058dc2e367b09e4e23e070817a7f6913d6a3dfe18af1c8f2c182bd67d3893fa290969edd154d80791

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
